---
title: "final_p"
output: html_document
---

```{r}
library(tidyverse)
data = read_csv("survey_results_public.csv") #read the file
data
```





```{r}


```


```{r }

#This code graphs a histogram by mostly used languages in decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data

library(wordcloud) 
library(highcharter)

languae_hist = data%>% 
  filter(Employment %in% 'Employed full-time') %>%  #filter full-time employees
  filter(!is.na(LanguageWorkedWith))%>% #filter missing data
  filter(!is.na(DevType)) %>% 
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>% #filter data scientists     
  filter(Country %in% 'United States') %>% #filter US workers
  select(LanguageWorkedWith)%>% 
  mutate(LanguageWorkedWith = str_split(LanguageWorkedWith, pattern = ";"))%>%
  unnest(LanguageWorkedWith)%>%
  group_by(LanguageWorkedWith)%>%
  summarise(Count = n())%>% #count by languages
  arrange(desc(Count))%>% #reorder in descending order
  ungroup()%>%
  mutate(LanguageWorkedWith = reorder(LanguageWorkedWith, Count))


#slice only top 20 data 
languae_hist = slice(languae_hist, 0:20) 

highchart()%>% #
  hc_title(text = paste("Mostly Used Language"))%>% #title
  hc_xAxis(categories = languae_hist$LanguageWorkedWith)%>% #xaxis
  hc_add_series(data = languae_hist$Count, name = "Count", type = "bar") #plot


#This code graphs a histogram by mostly used database in decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data


languae_hist = data%>% 
  filter(Employment %in% 'Employed full-time') %>%  #filter full-time employees
  filter(!is.na(DatabaseWorkedWith))%>% #filter missing data
  filter(!is.na(DevType)) %>% 
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>% #filter data scientists     
  filter(Country %in% 'United States') %>% #filter US workers
  select(DatabaseWorkedWith)%>% 
  mutate(DatabaseWorkedWith = str_split(DatabaseWorkedWith, pattern = ";"))%>%
  unnest(DatabaseWorkedWith)%>%
  group_by(DatabaseWorkedWith)%>%
  summarise(Count = n())%>% #count by database
  arrange(desc(Count))%>% #reorder in descending order
  ungroup()%>%
  mutate(DatabaseWorkedWith = reorder(DatabaseWorkedWith, Count))


#slice only top 20 data 
languae_hist = slice(languae_hist, 0:20) 

#plot in histogram
highchart()%>% #
  hc_title(text = paste("Mostly Used Database"))%>% #title
  hc_xAxis(categories = languae_hist$DatabaseWorkedWith)%>% #xaxis
  hc_add_series(data = languae_hist$Count, name = "Count", type = "bar") #plot


#This code graphs a histogram by mostly used platforms in decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data

languae_hist = data%>% 
  filter(Employment %in% 'Employed full-time') %>%  #filter full-time employees
  filter(!is.na(PlatformWorkedWith))%>% #filter missing data
  filter(!is.na(DevType)) %>% 
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>% #filter data scientists     
  filter(Country %in% 'United States') %>% #filter US workers
  select(PlatformWorkedWith)%>% 
  mutate(PlatformWorkedWith = str_split(PlatformWorkedWith, pattern = ";"))%>%
  unnest(PlatformWorkedWith)%>%
  group_by(PlatformWorkedWith)%>%
  summarise(Count = n())%>% #count by languages
  arrange(desc(Count))%>% #reorder in descending order
  ungroup()%>%
  mutate(PlatformWorkedWith = reorder(PlatformWorkedWith, Count))


#slice only top 20 data 
languae_hist = slice(languae_hist, 0:20) 

#plot
highchart()%>% #
  hc_title(text = paste("Mostly Used Platform"))%>% #title
  hc_xAxis(categories = languae_hist$PlatformWorkedWith)%>% #xaxis
  hc_add_series(data = languae_hist$Count, name = "Count", type = "bar") #plot






```


```{r}

#This code graphs a histogram of median salary by mostly used languages by decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data


library(wordcloud)
library(highcharter)

median_sal_lang = data%>%
  filter(Employment %in% 'Employed full-time') %>% 
  filter(!is.na(LanguageWorkedWith))%>%
  filter(!is.na(DevType)) %>%
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>%     filter(Country %in% 'United States') %>%
  select(LanguageWorkedWith,ConvertedSalary) %>% #The data already converted salaries to USD
  mutate(LanguageWorkedWith = str_split(LanguageWorkedWith, pattern = ";")) %>%
  unnest(LanguageWorkedWith) %>%
  group_by(LanguageWorkedWith) %>%
  summarise(Median_Salary = median(ConvertedSalary,na.rm = TRUE)) %>% #summarise each language by salary
  arrange(desc(Median_Salary))%>% #descending order
  ungroup()%>%
  mutate(LanguageWorkedWith = reorder(LanguageWorkedWith, Median_Salary))

#slice top 20 data
median_sal_lang = slice(median_sal_lang, 0:20)

#plot
highchart()%>%
  hc_title(text = paste("Median Salary by Language"))%>%
  hc_xAxis(categories = median_sal_lang$LanguageWorkedWith)%>%
  hc_add_series(data = median_sal_lang$Median_Salary, name = "Median Salary", type = "bar")



```

```{r}

#This code graphs a histogram of median salary by mostly used database by decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data

library(wordcloud)
library(highcharter)

median_sal_db = data%>%
  filter(Employment %in% 'Employed full-time') %>% 
  filter(!is.na(DatabaseWorkedWith))%>%
  filter(!is.na(DevType)) %>%
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>%     filter(Country %in% 'United States') %>%
  select(DatabaseWorkedWith,ConvertedSalary) %>% #The data already converted salaries to USD
  mutate(DatabaseWorkedWith = str_split(DatabaseWorkedWith, pattern = ";")) %>%
  unnest(DatabaseWorkedWith) %>%
  group_by(DatabaseWorkedWith) %>%
  summarise(Median_Salary = median(ConvertedSalary,na.rm = TRUE)) %>% #summarise each language by salary
  arrange(desc(Median_Salary))%>% #descending order
  ungroup()%>%
  mutate(DatabaseWorkedWith = reorder(DatabaseWorkedWith, Median_Salary))
#slice top 20 data
median_sal_db = slice(median_sal_db, 0:20)
#plot
highchart()%>%
  hc_title(text = paste("Median Salary by Database"))%>%
  hc_xAxis(categories = median_sal_db$DatabaseWorkedWith)%>%
  hc_add_series(data = median_sal_db$Median_Salary, name = "Median Salary", type = "bar")

```



```{r}

library(wordcloud)
library(highcharter)
#This code graphs a histogram of median salary by mostly used database by decreasing order.
#Filters full-time workers, Data Scientists, US workers, and their missing data
median_sal_plat = data%>%
  filter(Employment %in% 'Employed full-time') %>% 
  filter(!is.na(PlatformWorkedWith))%>%
  filter(!is.na(DevType)) %>%
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>%     filter(Country %in% 'United States') %>%
  select(PlatformWorkedWith,ConvertedSalary) %>% #The data already converted salaries to USD
  mutate(PlatformWorkedWith = str_split(PlatformWorkedWith, pattern = ";")) %>%
  unnest(PlatformWorkedWith) %>%
  group_by(PlatformWorkedWith) %>%
  summarise(Median_Salary = median(ConvertedSalary,na.rm = TRUE)) %>% #summarise each language by salary
  arrange(desc(Median_Salary))%>% #descending order
  ungroup()%>%
  mutate(PlatformWorkedWith = reorder(PlatformWorkedWith, Median_Salary))

#slice top 20
median_sal_plat = slice(median_sal_plat, 0:20)

highchart()%>%
  hc_title(text = paste("Median Salary by Platform"))%>%
  hc_xAxis(categories = median_sal_plat$PlatformWorkedWith)%>%
  hc_add_series(data = median_sal_plat$Median_Salary, name = "Median Salary", type = "bar")


```


```{r}

library(tidyverse)
library(ggplot2)
library(highcharter)
library(plotly)
library(stringr)
library(viridis)
library(gridExtra)
library(tidyverse)
library(highcharter)
library(plotly)
library(dygraphs)
library(lubridate)
library("viridisLite")
library(countrycode)
library(leaflet)
library(xts)
library(htmltools)

#This code shows world map by salaries(USD) of Data Scientists 


by_country_salary <- data %>% select(Country, ConvertedSalary, DevType) %>%
   filter(!is.na(DevType)) %>%
  filter(DevType %in% c('Data or business analyst','Data scientist or machine learning specialist')) %>% #filter data scientists
  mutate(ConvertedSalary=as.numeric(ConvertedSalary))  %>% filter(!is.na(Country)) %>% filter(!is.na(ConvertedSalary)) %>%
  group_by(Country) %>% summarize(MedSalary = median(ConvertedSalary, na.rm=TRUE))

data(worldgeojson, package = "highcharter") #using highcharter
code <- countrycode(by_country_salary$Country, 'country.name', 'iso3c') #get country code
by_country_salary$iso3 <- code
by_country_salary$MedSalary <- round(by_country_salary$MedSalary) #round

#plot
highchart() %>% 
  hc_add_series_map(worldgeojson, by_country_salary, value = "MedSalary", joinBy = "iso3",colorByPoint =  1) %>% 
  hc_colorAxis(stops = color_stops()) %>% 
  hc_legend(enabled = TRUE) %>%  
  #hc_mapNavigation(enabled = TRUE) %>%
  hc_title(text = "Median Salary by Country")  %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "",
            pointFormat = "Country: {point.Country} Median Salary: ${point.MedSalary}") %>% hc_add_theme(hc_theme_google())
```
